### ISSUE TITLE
matmul issue with test sites

### ISSUE THREAD

**Issue by Mahmou-Abdullah** [lindsey98/Phishpedia#29]
Hi
I've been trying to get phishpedia to work with the provided test sites for a while but unfortunately I couldn't. I followed the installation steps outlined in the repo's README.md but every time I try to run the script it throws an exception in file `phishpedia.py` line 157. Here is the output

```
(phishpedia) root@041371539a6d:~/phish/Phishpedia# ls datasets/
.DS_Store     overview.png  test_sites/
(phishpedia) root@041371539a6d:~/phish/Phishpedia# ls datasets/test_sites/accounts.g.cdcde.com/
info.txt  shot.png
(phishpedia) root@041371539a6d:~/phish/Phishpedia# python phishpedia.py --folder ./datasets/test_sites/
The checkpoint state_dict contains keys that are not used by the model:
  pixel_mean
  pixel_std
Load protected logo list
Length of reference list = 0
  0%|                                                                                                                                                               | 0/1 [00:00<?, ?it/s]Entering phishpedia
Entering siamese
number of logo boxes: 2
  0%|                                                                                                                                                               | 0/1 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "phishpedia.py", line 157, in <module>
    logo_recog_time, logo_match_time = phishpedia_cls.test_orig_phishpedia(url, screenshot_path)
  File "phishpedia.py", line 73, in test_orig_phishpedia
    pred_target, matched_domain, matched_coord, siamese_conf = check_domain_brand_inconsistency(logo_boxes=pred_boxes,
  File "/root/phish/Phishpedia/logo_matching.py", line 36, in check_domain_brand_inconsistency
    matched_target, matched_domain, this_conf = pred_brand(model, domain_map,
  File "/root/phish/Phishpedia/logo_matching.py", line 166, in pred_brand
    sim_list = logo_feat_list @ img_feat.T  # take dot product for every pair of embeddings (Cosine Similarity)
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2048 is different from 0)
```

**Comment by lindsey98** [comment]
Hi,
   Can you check whether this folder ``models/expand_targetlist`` exists, if not please unzip the ``models/expand_targetlist.zip``.

**Comment by Mahmou-Abdullah** [comment]
> Hi, Can you check whether this folder `models/expand_targetlist` exists, if not please unzip the `models/expand_targetlist.zip`.

Thank you! It works. Looks like I didn't have zip installed in the docker image.
