### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by Xiaoxiaodewo89** [lindsey98/Phishpedia#30]
Traceback (most recent call last):
  File "phishpedia.py", line 157, in <module>
    logo_recog_time, logo_match_time = phishpedia_cls.test_orig_phishpedia(url, screenshot_path)
  File "phishpedia.py", line 73, in test_orig_phishpedia
    pred_target, matched_domain, matched_coord, siamese_conf = check_domain_brand_inconsistency(logo_boxes=pred_boxes,
  File "/home/cug/Phishpedia/logo_matching.py", line 46, in check_domain_brand_inconsistency
    if tldextract.extract(url).domain in matched_domain: # domain and brand are consistent
TypeError: argument of type 'NoneType' is not iterable

**Comment by Xiaoxiaodewo89** [comment]
Solved
logo_matching.py    line 46   
replace  
 if tldextract.extract(url).domain in matched_domain: # domain and brand are consistent
with
 if matched_domain is not None and tldextract.extract(url).domain in matched_domain:  # domain and brand are consistent
